#!/bin/bash

#base dir in $1
#filename in $2

region="Veracruz, Mexico, North America, Latin America"
name="INECOL_crop_dataset_2019"
title="INECOL crop dataset for Veracruz state 2019"
kw="INECOL"
abstract="Crop dataset for Veracruz state generated by INECOL in 2019. Attributes: fecha, municipio, distritodr, ecoregion, zonadevida, cultivo, asociacion, x, y, observ."

import_small_medium_size_vector --input_directory $1 --input_filename $2 --destiny_path /data/var/ftp/pub/ --list_attributes "Fecha, Municipio, DistritoDR, Ecoregion, ZonadeVida, Cultivo, Asociacion, Observ" --region "$region" --name "$name" --title "$title" --abstract "$abstract" --key_words "$kw"